spring:
  datasource:
    url: jdbc:mysql://10.10.10.102:3306/temp?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gaiga
    password: gaiga
    
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  
logging:
  level:
    org.hibernate: info
    org.springframework: info
    org.kidding: info
      
  